apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod2
  labels: 
    app: frontend
spec:
  containers:
    - name: nginx-container
      image: nginx:latest
      ports:
        - containerPort: 80