version: '3.9'
services:
  postgres:
    image: postgres:latest
    environment:
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PW}
        - POSTGRES_DB=${POSTGRES_DB}
    ports:
      - "5433:5432"
    restart: always